### ISSUE TITLE
Capybara::Poltergeist::TimeoutError

### ISSUE THREAD

**Issue by bipashant** [midwire/tr4n5l4te#2]
Hi there!
Thank you for this amazing work.
 I'm trying to translate this file 
[https://github.com/sharetribe/sharetribe/blob/master/config/locales/en.yml](https://github.com/sharetribe/sharetribe/blob/master/config/locales/en.yml)
but every time I run the command `./exe/translate -y en.yml -l Arabic -s 3`
I get the following error, 

**Steps to reproduce** 

I'm trying this from Digital Ocean Server in order to make it faster,
I cloned the repo
place my en.yml file inside the repo folder then run this command  `./exe/translate -y en.yml -l Arabic -s 3`

Is there anything I need to do in addition to this?
Any suggestion will be appreciated.
```root@uexperience:~/app/tr4n5l4te# ./exe/translate -y en.yml -l Arabic -s 2
Starting Tr4n5l4te v0.1.3 @14:20:16.705
   
/usr/local/rvm/gems/ruby-2.3.4/gems/poltergeist-1.16.0/lib/capybara/poltergeist/web_socket_server.rb:100:in `rescue in send': Timed out waiting for response to {"id":"7668152d-5e95-4338-933d-19374d4198fe","name":"find","args":["css","#result_box"]}. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the Poltergeist :timeout option to a higher value will help (see the docs for details). If increasing the timeout does not help, this is probably a bug in Poltergeist - please report it to the issue tracker. (Capybara::Poltergeist::TimeoutError)
	from /usr/local/rvm/gems/ruby-2.3.4/gems/poltergeist-1.16.0/lib/capybara/poltergeist/web_socket_server.rb:96:in `send'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/poltergeist-1.16.0/lib/capybara/poltergeist/server.rb:43:in `send'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/poltergeist-1.16.0/lib/capybara/poltergeist/browser.rb:370:in `command'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/poltergeist-1.16.0/lib/capybara/poltergeist/browser.rb:64:in `find'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/poltergeist-1.16.0/lib/capybara/poltergeist/driver.rb:122:in `find'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/poltergeist-1.16.0/lib/capybara/poltergeist/driver.rb:130:in `find_css'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/node/base.rb:103:in `find_css'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/queries/selector_query.rb:148:in `block in resolve_for'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/node/base.rb:81:in `synchronize'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/queries/selector_query.rb:146:in `resolve_for'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/node/finders.rb:304:in `block in synced_resolve'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/node/base.rb:85:in `synchronize'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/node/finders.rb:302:in `synced_resolve'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/node/finders.rb:37:in `find'
	from /usr/local/rvm/gems/ruby-2.3.4/gems/capybara-2.15.4/lib/capybara/session.rb:792:in `block (2 levels) in <class:Session>'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/translator.rb:18:in `translate'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:44:in `translate'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:36:in `block in process'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `each'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `each_with_object'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `process'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:36:in `block in process'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `each'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `each_with_object'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `process'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:36:in `block in process'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `each'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `each_with_object'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `process'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:36:in `block in process'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `each'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `each_with_object'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `process'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:36:in `block in process'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `each'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `each_with_object'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:34:in `process'
	from /root/app/tr4n5l4te/lib/tr4n5l4te/runner.rb:25:in `run'
	from ./exe/translate:9:in `<main>'`

**Comment by midwire** [comment]
@bipashant, I'm running it now on your file with the same command line. It hasn't timed out yet, but I'm adding a command-line option to bump up the timeout value for Poltergeist which may help. It is possible that a particular string caused google translate to hang. I'll post the changes ASAP.

**Comment by bipashant** [comment]
Thank you bro!
God bless you!

**Comment by midwire** [comment]
@bipashant i've pushed some changes to the `develop` branch that will allow you to set the timeout value for poltergeist. If that works for you I'll merge that into `master` and push a new gem version. Let me know.
