### ISSUE TITLE
Could not determine language from yaml file

### ISSUE THREAD

**Issue by Sohair63** [midwire/tr4n5l4te#6]
command I am using: 

`translate -y config/locales/en.yml -l Spanish`

result in 

```
`from_lang': Could not determine language from yaml file: 'config/locales/en.yml' (RuntimeError)
	from /Users/square63/.rvm/gems/ruby-2.3.3/gems/tr4n5l4te-0.1.4/lib/tr4n5l4te/runner.rb:49:in `translate'
	from /Users/square63/.rvm/gems/ruby-2.3.3/gems/tr4n5l4te-0.1.4/lib/tr4n5l4te/runner.rb:41:in `block in process'
	from /Users/square63/.rvm/gems/ruby-2.3.3/gems/tr4n5l4te-0.1.4/lib/tr4n5l4te/runner.rb:39:in `each'
	from /Users/square63/.rvm/gems/ruby-2.3.3/gems/tr4n5l4te-0.1.4/lib/tr4n5l4te/runner.rb:39:in `each_with_object'
	from /Users/square63/.rvm/gems/ruby-2.3.3/gems/tr4n5l4te-0.1.4/lib/tr4n5l4te/runner.rb:39:in `process'
	from /Users/square63/.rvm/gems/ruby-2.3.3/gems/tr4n5l4te-0.1.4/lib/tr4n5l4te/runner.rb:41:in `block in process'
	from /Users/square63/.rvm/gems/ruby-2.3.3/gems/tr4n5l4te-0.1.4/lib/tr4n5l4te/runner.rb:39:in `each'
	from /Users/square63/.rvm/gems/ruby-2.3.3/gems/tr4n5l4te-0.1.4/lib/tr4n5l4te/runner.rb:39:in `each_with_object'
	from /Users/square63/.rvm/gems/ruby-2.3.3/gems/tr4n5l4te-0.1.4/lib/tr4n5l4te/runner.rb:39:in `process'
	from /Users/square63/.rvm/gems/ruby-2.3.3/gems/tr4n5l4te-0.1.4/lib/tr4n5l4te/runner.rb:41:in `block in process'
	from /Users/square63/.rvm/gems/ruby-2.3.3/gems/tr4n5l4te-0.1.4/lib/tr4n5l4te/runner.rb:39:in `each'
	from /Users/square63/.rvm/gems/ruby-2.3.3/gems/tr4n5l4te-0.1.4/lib/tr4n5l4te/runner.rb:39:in `each_with_object'
	from /Users/square63/.rvm/gems/ruby-2.3.3/gems/tr4n5l4te-0.1.4/lib/tr4n5l4te/runner.rb:39:in `process'
	from /Users/square63/.rvm/gems/ruby-2.3.3/gems/tr4n5l4te-0.1.4/lib/tr4n5l4te/runner.rb:30:in `run'
	from /Users/square63/.rvm/gems/ruby-2.3.3/gems/tr4n5l4te-0.1.4/exe/translate:9:in `<top (required)>'
	from /Users/square63/.rvm/gems/ruby-2.3.3/bin/translate:23:in `load'
	from /Users/square63/.rvm/gems/ruby-2.3.3/bin/translate:23:in `<main>'
	from /Users/square63/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/square63/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by midwire** [comment]
@Sohair63 sorry for the delay. Can you attach your .yml file?

**Comment by Branksy** [comment]
Getting same response for en.yml:

en:
  time:
    formats:
      default: "%B %d %Y %H:%M"
  bands:
    rolling_stones: "The Rolling Stones"
    beatles: "The Beatles"
    acdc: "AC/DC"
